# Generated by Django 5.0.6 on 2024-07-07 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(blank=True, error_messages={'unique': 'A user with that phone number already exists.'}, null=True, validators=[django.core.validators.RegexValidator('^989[0-3,9]\\d{8}$', 'Enter a valid phone number', 'invalid')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='required. 30 characters or fewer starting with a letter. Letters, digits and ', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9_\\.]+$', 'enter a valid username starting with a a_z', 'this value my contain only letters, numbers and', 'and underscore characters', 'invalid')], verbose_name='username'),
        ),
    ]
