# Generated by Django 4.2 on 2024-07-03 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_file_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='products.product', verbose_name='product_id'),
        ),
    ]
